### ISSUE TITLE
Permanently shows update available + Lua error

### ISSUE THREAD

**Issue by filliph** [Jodsderechte/DungeonAuraTools#59]
### Description

After every reload, the following messages appear:
```
[12:51:49 PM] DungeonAuraTools: 1  Auras that have Updates detected. They have been send to Weakauras please import them by Opening the WeakAura option 
[12:51:49 PM] WeakAuras:  There are 1 updates to your auras ready to be installed!
```
It is not possible to clear this message as the update is broken.

### WeakAuras Version

5.2.0

### DungeonAuraTools Version

1.0.4

### Tested with only WeakAuras and DungeonAuraTools

- [X] Yes
- [ ] No

### Lua Error

```
30x ...idgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:152: attempt to index local 'data' (a nil value)
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua"]:152: in function `SetNormalTooltip'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua"]:80: in function <...idgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:79>
```

### Reproduction Steps

1. Delete all DAT auras
2. `/reload`
3. In the WeakAuras Companion app, click Check Update
4. Leave WA Companion app running
5. Run `/dat export` and import all WAs
6. `/reload`

Message from step 1 will show, and mousing over the spinning blue update button shows the above Lua error.

### Last Good Version

N/A

### Screenshots

N/A

**Comment by Jodsderechte** [comment]
can you drop me your saved variables from WTF\Account\<Account #>\SavedVariables\DungeonAuraTools.lua

**Comment by filliph** [comment]
I tells ya, back in my day, we didn't have no dang numbers in our account names! We made our Blizzard accounts uphill both ways in 40ft of snow, and the most exciting part of a new expansion launch was seeing the new launcher colour, and we liked it that way! 👴 

[DungeonAuraTools.zip](https://github.com/Jodsderechte/DungeonAuraTools/files/10094098/DungeonAuraTools.zip)

**Comment by Jodsderechte** [comment]
Ah you never selected any of the options in the addon i'll need to do some digging!

**Comment by filliph** [comment]
Last time I accessed the options for this add-on was w.r.t. https://github.com/Jodsderechte/DungeonAuraTools/issues/27 🤔 

I'll leave it as-is for now so I can help test a fix, I'm not doing any keys for a week or two anyway! 😄

**Comment by Jodsderechte** [comment]
still need to investigate about the lua error but the permanent exporting is fixed

**Comment by filliph** [comment]
Neither of these issues have been resolved in 1.0.5, sorry to say :(

DungeonAuras_Dragonflight will show as the broken blue update icon after:
1. Logout
2. Click check for update in WA Companion
3. Login again

I've also checked the options and one hundred percent of settings under every category and sub-category of Dragonflight are ticked. For affixes, I've unticked Busy Trader and Necrotic, as those affixes do not exist in 10.0.

**Comment by Beet4** [comment]
I also get the update notification from WA Companion app when using the AddOn (1.0.6). I've cleaned all WA and re-exported them from the addon but after doing that and launching WA Companion it still shows an update.

Let me know if you need something from me to debug.

![image](https://user-images.githubusercontent.com/38279393/204111976-2d6c1a89-f98d-42cc-aff6-cbd3c3ed844c.png)

![image](https://user-images.githubusercontent.com/38279393/204111983-2757f181-1405-41cd-a246-671f9f5cbdc9.png)

**Comment by Jodsderechte** [comment]
that is very odd  i'll need to do more investigating

**Comment by Halvi3** [comment]
Chiming in to +1 @Beet4 's report, I tried deleting all the addons from within WeakAuras' interface, uninstalling and reinstalling the DAT addon itself, and re-exporting all the auras, and immediately get the exact same update prompt as in that screenshot

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/204330023-097368e9-271f-4551-bfae-f22155d5bf8f.png)
Same issue on my end, applying the updates does not even dismiss it from WA's either.

**Comment by Beet4** [comment]
WeakAuras Companion no longer says there is an update but WeakAuras still says there is an update for Dragonflight Dungeons. 

Now the DAT addon now says there is an update to the Affixes WA as well but I get a LUA error when hovering over the update icon in WeakAuras. This only happens when hovering over the blue icon button for affixes and not the normal one for Dragonflight Dungeons (which does not update when update it, still says there is an update).

![image](https://user-images.githubusercontent.com/38279393/205228281-d9ea8b64-7ae8-48be-8832-4c284dcb1480.png)

```
47x ...idgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:153: attempt to index local 'data' (a nil value)
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua"]:153: in function `SetNormalTooltip'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua"]:81: in function <...idgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:80>

Locals:
self = <table> {
 Enable = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:129
 update = Button {
 }
 MarkLinkedChildren = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:205
 background = Texture {
 }
 icon = Texture {
 }
 linkedChildren = <table> {
 }
 AceGUIWidgetVersion = 4
 ReleaseThumbnail = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:223
 hasThumbnail = false
 SetNormalTooltip = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:149
 title = FontString {
 }
 Initialize = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:52
 SetTitle = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:191
 Disable = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:125
 OnRelease = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:137
 callbacks = <table> {
 }
 OnAcquire = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:47
 SetIcon = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:265
 parent = <table> {
 }
 menu = <table> {
 }
 base = <table> {
 }
 SetLogo = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:119
 SetDescription = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:188
 AcquireThumbnail = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:239
 type = "WeakAurasPendingUpdateButton"
 linkedAuras = <table> {
 }
 companionData = <table> {
 }
 SetMenu = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:86
 id = "DungeonAuras_Affixes"
 SetRefreshLogo = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:122
 titletext = "DungeonAuras_Affixes"
 userdata = <table> {
 }
 ResetLinkedAuras = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:198
 events = <table> {
 }
 UpdateThumbnail = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:208
 updateLogo = Frame {
 }
 frame = WeakAurasPendingUpdateButton1 {
 }
 SetClick = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:195
 MarkLinkedAura = <function> defined @WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua:202
}
data = nil
namestable = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'data' (a nil value)"
pairs = <function> defined =[C]:-1
L = <table> {
 No Instance = "No Instance"
 Scenario = "Scenario"
 Destination Reaction = "Destination Reaction"
 Icecrown Citadel = "Icecrown Citadel"
 Threat Value = "Threat Value"
 A 48x48 pixels icon = "A 48x48 pixels icon"
 Stacks = "Stacks"
 Aura(s) Missing = "Aura(s) Missing"
 Raid = "Raid"
 Armor against Target (%) = "Armor against Target (%)"
 Show Heal Absorb = "Show Heal Absorb"
 Show Rested Overlay = "Show Rested Overlay"
 Aggro = "Aggro"
 Alpha = "Alpha"
 Player Character = "Player Character"
 Tab  = "Tab "
 Down = "Down"
 Always active trigger = "Always active tri
```

**Comment by Jodsderechte** [comment]
ah so this bug is specifically tied to the affixes aura thats good to know and will make debugging easier thanks!

**Comment by Beet4** [comment]
Also, when pressing the update-button which throws the LUA error on hover I get the follwing error message:
![image](https://user-images.githubusercontent.com/38279393/205253105-91890675-27c8-465a-9b38-ea670169d9e4.png)

**Comment by Halvi3** [comment]
With the above information I tried clearing and re-importing all auras having _unchecked_ the 'Anchor to Affix' option and now only DungeonAuras_Affixes is stuck showing a permanent update available, the prompt to update Dragonflight Dungeons no longer shows up
